< !doctype html > < html lang = "en" > < head > < meta charset = "UTF-8" > < meta http - equiv = "X-UA-Compatible"
content = "IE=edge" > < meta name = "viewport"
content = "width=device-width,initial-scale=1" > < title > Page Not Found < /title><link rel="canonical" href="https:/ / www.guvi.in / 404 / "><meta name="
viewport " content="
width = device - width, initial - scale = 1, shrink - to - fit = no "><link rel="
shortcut icon " href=" / web - build / images / favicons / favicon.ico "><link rel="
icon " type="
image / png " sizes="
16 x16 " href=" / web - build / images / favicons / favicon - 16 x16.png "><link rel="
icon " type="
image / png " sizes="
32 x32 " href=" / web - build / images / favicons / favicon - 32 x32.png "><link rel="
icon " type="
image / png " sizes="
48 x48 " href=" / web - build / images / favicons / favicon - 48 x48.png "><link rel="
manifest " href=" / web - build / images / favicons / manifest.json "><meta name="
mobile - web - app - capable " content="
yes "><meta name="
theme - color " content="#
fff "><meta name="
application - name " content="
GUVI "><link rel="
apple - touch - icon " sizes="
57 x57 " href=" / web - build / images / favicons / apple - touch - icon - 57 x57.png "><link rel="
apple - touch - icon " sizes="
60 x60 " href=" / web - build / images / favicons / apple - touch - icon - 60 x60.png "><link rel="
apple - touch - icon " sizes="
72 x72 " href=" / web - build / images / favicons / apple - touch - icon - 72 x72.png "><link rel="
apple - touch - icon " sizes="
76 x76 " href=" / web - build / images / favicons / apple - touch - icon - 76 x76.png "><link rel="
apple - touch - icon " sizes="
114 x114 " href=" / web - build / images / favicons / apple - touch - icon - 114 x114.png "><link rel="
apple - touch - icon " sizes="
120 x120 " href=" / web - build / images / favicons / apple - touch - icon - 120 x120.png "><link rel="
apple - touch - icon " sizes="
144 x144 " href=" / web - build / images / favicons / apple - touch - icon - 144 x144.png "><link rel="
apple - touch - icon " sizes="
152 x152 " href=" / web - build / images / favicons / apple - touch - icon - 152 x152.png "><link rel="
apple - touch - icon " sizes="
167 x167 " href=" / web - build / images / favicons / apple - touch - icon - 167 x167.png "><link rel="
apple - touch - icon " sizes="
180 x180 " href=" / web - build / images / favicons / apple - touch - icon - 180 x180.png "><link rel="
apple - touch - icon " sizes="
1024 x1024 " href=" / web - build / images / favicons / apple - touch - icon - 1024 x1024.png "><meta name="
apple - mobile - web - app - capable " content="
yes "><meta name="
apple - mobile - web - app - status - bar - style " content="
black - translucent "><meta name="
apple - mobile - web - app - title " content="
GUVI "><script defer="
defer " src=" / web - build / 0.9828 b79aaa5999f21157.js "></script><script defer="
defer " src=" / web - build / 4.9828 b79aaa5999f21157.js "></script><script defer="
defer " src=" / web - build / 1.9828 b79aaa5999f21157.js "></script><script defer="
defer " src=" / web - build / 2.9828 b79aaa5999f21157.js "></script><script defer="
defer " src=" / web - build / 3.9828 b79aaa5999f21157.js "></script><script defer="
defer " src=" / web - build / 404.9828 b79aaa5999f21157.js "></script><link href=" / web - build / 1.1 .0 fdcc1956f3cfa47e748.css " rel="
stylesheet "><link href=" / web - build / 2.2 .3 b6e0745770a0050e63f.css " rel="
stylesheet "><link href=" / web - build / 404.7 baae362cd754ca1b3e3.css " rel="
stylesheet "><script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create','UA-53114947-1','auto');ga('send','pageview');</script><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(), event: 'gtm.js'
});
var f = d.getElementsByTagName(s)[0],
    j = d.createElement(s),
    dl = l != 'dataLayer' ? '&l=' + l : '';
j.async = true;
j.src =
    'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
f.parentNode.insertBefore(j, f);
})(window, document, 'script', 'dataLayer', 'GTM-5WRCCN9'); < /script></head > < body > < noscript > < iframe src = "https://www.googletagmanager.com/ns.html?id=GTM-5WRCCN9"
height = "0"
width = "0"
style = "display:none;visibility:hidden" > < /iframe></noscript > < header class = "bg-white no-reload" > < nav class = "navbar-expand-lg col-md-12 mx-auto" > < div class = "container-fluid" > < div class = "d-flex" > < div class = "d-flex mr-auto" > < button class = "navbar-toggler"
type = "button"
data - toggle = "collapse"
data - target = "#navbarSupportedContent"
aria - controls = "navbarSupportedContent"
aria - expanded = "false"
aria - label = "Toggle navigation" > < i class = "fa fa-bars"
aria - hidden = "true" > < /i></button > < a href = "/"
class = "head-guvi-logo" > < img src = "/web-build/images/new-guvi-logo.c5a97b2fca3329f4bb8d2b992a2f1ed9.png"
width = "95px"
alt = "" > < /a></div > < div class = "d-flex" > < div class = "collapse navbar-collapse"
id = "navbarSupportedContent" > < ul class = "navbar-nav" > < li class = "nav-item dropdown" > < a class = "nav-link dropdown-toggle down-icon evtCourses"
href = "/courses/" > Courses < /a></li > < li class = "nav-item dropdown" > < a class = "nav-link dropdown-toggle down-icon real-toggle"
href = "#"
id = "navbarDropdown"
role = "button"
data - toggle = "dropdown"
aria - haspopup = "true"
aria - expanded = "false" > LIVE Classes < i class = "fa fa-angle-down ml-1"
aria - hidden = "true" > < /i></a > < div class = "dropdown-menu nav-first-tab"
aria - labelledby = "navbarDropdown" > < ul class = "pl-0 pt-3 pb-3 course-categrori" > < li class = "pointer-events-none" > < div > < p class = "heading" > Zen Class < span class = "badge badge-secondary ml-3" > < i class = "fa fa-circle mr-2"
aria - hidden = "true" > < /i>Live Online Classes</span > < /p><p>LIVE Online Intensive Program + Placement Guidance</p > < hr > < /div></li > < li > < a href = "/zen-class/full-stack-development-course/" > < p class = "heading" > IIT - M Pravartak Certified Full Stack Development Program(FSD) < /p><p>Learn Javascript, HTML, CSS, Java, Data Structure, MongoDB & more</p > < /a></li > < li > < a href = "/zen-class/data-science-course/" > < p class = "heading" > IIT - M Pravartak Certified Data Science Program < /p><p>Learn Python, Machine Learning, NLP, Tableau, PowerBI & more</p > < /a></li > < li > < a href = "/zen-class/automation-testing-course/" > < p class = "heading" > Automation & Testing Program < /p><p>Learn Selenium, Python, Java, Jenkins, Jmeter, API Testing & more</p > < /a></li > < li > < a href = "/zen-class/"
class = "nav-live-class" > Explore More Programs < /a></li > < /ul></div > < /li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle down-icon real-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Practice <i class="fa fa-angle-down ml-1" aria-hidden="true"></i > < /a><div class="dropdown-menu nav-scound-tab" aria-labelledby="navbarDropdown"><ul class="pl-0 pt-3 pb-3 course-categrori"><li><a href="/code - kata / "><p class="
heading ">Codekata</p><p>Sharpen your coding skills, prepare for interviews</p></a></li><li><a href=" / webkata / "><p class="
heading ">Webkata</p><p>Build basic Frontend and Backend development skills</p></a></li><li><a href=" / debugging / "><p class="
heading ">Debugging</p><p>A series of programs curated by Industry Experts</p></a></li><li><a href=" / ide / "><p class="
heading ">IDE - Online Compiler</p><p>Run & test your code in any programming language</p></a></li></ul></div></li><li class="
nav - item dropdown "><a class="
nav - link dropdown - toggle down - icon real - toggle " href="#
" id="
navbarDropdown " role="
button " data-toggle="
dropdown " aria-haspopup="
true " aria-expanded="
false ">Resources <i class="
fa fa - angle - down ml - 1 " aria-hidden="
true "></i></a><div class="
dropdown - menu nav - third - tab " aria-labelledby="
navbarDropdown "><ul class="
pl - 0 pt - 3 pb - 3 course - categrori "><li><a class="
learnhub pr - 2 " href=" / hub / ">Learn Hub <span class="
badge badge - danger pt - 1 ml - 1 ">New</span></a></li><li><a href=" / rewards / ">Rewards</a></li><li><a href=" / referral / ">Referral</a></li><li><a href="
https: //forum.guvi.in">Forum Support</a></li><li><a href="/blog/">Blogs</a></li><li><a href="https://play.google.com/store/apps/details?id=com.guviapp">App Download</a></li><li><a href="/guvi-affiliate/">Become an Affiliate</a></li></ul></div></li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle down-icon real-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Our Solutions <i class="fa fa-angle-down ml-1" aria-hidden="true"></i></a><div class="dropdown-menu nav-four-tab" aria-labelledby="navbarDropdown"><ul class="pl-0 pt-3 pb-3 course-categrori"><li><a href="https://www.hackerkid.org/"><p class="heading">HackerKid</p><p>Coding classes platform for K-12 children</p></a></li><li><a href="/mlp/GUVI-for-corporates"><p class="heading">GUVI for Corporates</p><p>Meet your Hiring & Training Needs</p></a></li><li><a href="https://www.placementpreparation.io/?utm_source=navigation_menu&utm_medium=guvi_website&utm_campaign=launch_cross_promotion_nav_menu"><p class="heading">Placement Preparation</p><p>Ace Up your Aptitude</p></a></li></ul></div></li></ul></div><div class="d-flex head-user-profile" id="accountGroup"></div></div></div></div></nav></header><div class="menu-sidebar-modal"><div class="bg-white sub-menu-dropdown"><div class="d-flex w-100 p-3"><a href="/" class="mr-auto"><img src="/web-build/images/new-guvi-logo.c5a97b2fca3329f4bb8d2b992a2f1ed9.png" width="90px"></a><a href="javascript:void(0)" class="menu-sidebar-close"><span class="material-icons">close</span></a></div><div id="accordion"><div class="card"><a href="/courses/">Courses</a></div><div class="card"><div id="headingOne"><button class="w-100 d-flex" data-toggle="collapse" data-target="#Learn" aria-expanded="true" aria-controls="collapseOne"><p class="mr-auto">LIVE Classes</p><i class="fa fa-angle-down" aria-hidden="true"></i></button></div><div id="Learn" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion"><ul class="pl-0 pt-3 pb-3 mb-0 course-categrori"><li><a disabled="disabled" href="#" class="white-bg-over pb-0"><p class="heading">Zen Class <span class="badge badge-secondary ml-3"><i class="fa fa-circle mr-2" aria-hidden="true"></i>Live Online Classes</span></p><p>LIVE Online Intensive Program + Placement Guidance</p><hr class="mt-3"></a></li><li><a href="/zen-class/full-stack-development-course/"><p class="heading">Full Stack Development Program (FSD)</p><p>Learn Javascript, HTML, CSS, Java, Data Structure, MongoDB & more</p></a></li><li><a href="/zen-class/data-science-course/"><p class="heading">IIT-M Pravartak Certified Data Science Program</p><p>Learn Python, Machine Learning, NLP, Tableau, PowerBI & more</p></a></li><li><a href="/zen-class/automation-testing-course/"><p class="heading">Automation & Testing Program</p><p>Learn Selenium, Python, Java, Jenkins, Jmeter, API Testing & more</p></a></li><li><a href="/zen-class/" class="nav-live-class">Explore More Programs</a></li></ul></div></div><div class="card"><div id="headingOne"><button class="w-100 d-flex" data-toggle="collapse" data-target="#Practice" aria-expanded="true" aria-controls="collapseOne"><p class="mr-auto">Practice</p><i class="fa fa-angle-down" aria-hidden="true"></i></button></div><div id="Practice" class="collapse" aria-labelledby="headingOne" data-parent="#accordion"><ul class="pl-0 pt-3 pb-3 course-categrori"><li><a href="/code-kata/"><p class="heading">Codekata</p><p>Sharpen your coding skills, prepare for interviews</p></a></li><li><a href="/webkata/"><p class="heading">Webkata</p><p>Build basic Frontend and Backend development skills</p></a></li><li><a href="/ide/"><p class="heading">IDE - Online Compiler</p><p>Run & test your code in any programming language</p></a></li></ul></div></div><div class="card"><div id="headingOne"><button class="w-100 d-flex" data-toggle="collapse" data-target="#Resourses" aria-expanded="true" aria-controls="collapseOne"><p class="mr-auto">Resources</p><i class="fa fa-angle-down" aria-hidden="true"></i></button></div><div id="Resourses" class="collapse" aria-labelledby="headingOne" data-parent="#accordion"><ul class="pl-0 course-categrori"><li><a href="/hub/">Learn Hub <span class="badge badge-danger pt-1 ml-1">New</span></a></li><li><a href="/rewards/">Rewards</a></li><li><a href="/referral/">Referral</a></li><li><a href="https://forum.guvi.in/">Forum Support</a></li><li><a href="/blog/">Blogs</a></li><li><a href="https://play.google.com/store/apps/details?id=com.guviapp">App Download</a></li><li><a href="/guvi-affiliate/">Become an Affiliate</a></li></ul></div></div><div class="card"><div id="headingOne"><button class="w-100 d-flex" data-toggle="collapse" data-target="#Products" aria-expanded="true" aria-controls="collapseOne"><p class="mr-auto">Our Products</p><i class="fa fa-angle-down" aria-hidden="true"></i></button></div><div id="Products" class="collapse" aria-labelledby="headingOne" data-parent="#accordion"><ul class="pl-0 course-categrori"><li><a href="https://www.hackerkid.org/"><p class="heading">HackerKid</p><p>Coding classes platform for K-12 children</p></a></li><li><a href="/mlp/GUVI-for-corporates"><p class="heading">GUVI for Corporates</p><p>Meet your Hiring & Training Needs</p></a></li><li><a href="https://www.placementpreparation.io/?utm_source=navigation_menu&utm_medium=guvi_website&utm_campaign=launch_cross_promotion_nav_menu"><p class="heading">Placement Preparation</p><p>Ace Up your Aptitude</p></a></li></ul></div></div><div class="card" id="signUpApp"><a href="/register/">Sign up</a></div><div class="card"><a href="/sign-in/" id="loginApp">Login</a></div></div></div></div><main role="main" class="container common-padding text-center no-tawk"><div class="row justify-content-center"><div class="col-10 col-md-8 col-lg-4"><img src="/web-build/images/not-found-logo.80dd906d7d6f0aa75e569bc9e51dd348.png" alt="Not-Found-Logo" title="Not Found Logo" loading="lazy" class="w-100"/></div></div><h1 class="mb-3">Error 404: Page Not Found!</h1><div class="row justify-content-center"><div class="col-12 col-md-10 col-lg-6 para"><p class="text mb-4">Whoops! Looks like you've found a page that doesn't exist. Don't worry, let’s help you get back to familiar pages...</p></div></div><div class="row justify-content-center btnDiv flex-wrap-reverse"><div class="col-12 col-md-6 col-lg-3"><a href="/courses/" class="btn darkBtn w-100 cta">Explore Self Paced Courses</a></div><div class="col-12 col-md-6 col-lg-3 mb-3 mb-lg-auto"><a href="/zen-class/" class="btn primaryBtn w-100 cta">Explore Live Classes</a></div></div><div class="pt-4 pb-5 homePageCta"><a href="/" class="text-primary cta">Go to Homepage</a></div></main><div class="spinner spinner-border" role="status"><span class="sr-only">Loading...</span></div></body></html>